# Generated by Django 6.0.2 on 2026-04-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
        ("subscriptions", "0005_subscription_badge"),
        ("transactions", "0005_asxequitylist_equity_alter_transaction_equity_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="equities",
            field=models.ManyToManyField(blank=True, to="transactions.equity"),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolios",
            field=models.ManyToManyField(blank=True, to="portfolios.portfolio"),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
    ]
