# Generated by Django 6.0.2 on 2026-03-16 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
