# Generated by Django 6.0.2 on 2026-03-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_rename_create_at_transaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="AUD", max_length=3),
        ),
    ]
