# Generated by Django 6.0.2 on 2026-03-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
        ("transactions", "0003_transaction_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="ticker",
        ),
        migrations.AddField(
            model_name="transaction",
            name="equity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolios.equity",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="portfolios.portfolio",
            ),
        ),
    ]
