# Generated by Django 6.0.2 on 2026-04-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_remove_transaction_ticker_transaction_equity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASXEquityList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=100)),
                ("currency", models.CharField(default="AUD", max_length=3)),
                ("exchange", models.CharField(default="ASX", max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="transaction",
            name="equity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.equity",
            ),
        ),
        migrations.CreateModel(
            name="EquityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("closing_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "equity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="transactions.equity",
                    ),
                ),
            ],
            options={
                "unique_together": {("equity", "date")},
            },
        ),
    ]
