# Generated by Django 6.0.2 on 2026-04-07 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_alter_asxequitylist_id_alter_equity_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="remaining_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TransactionMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_quantity", models.PositiveIntegerField()),
                (
                    "buy_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_matches_from_buy",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "sell_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_matches_for_sell",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
    ]
