# Generated by Django 6.0.2 on 2026-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0008_transaction_remaining_quantity_transactionmatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equityprice",
            name="closing_price",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
