# Generated by Django 6.0.2 on 2026-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0009_alter_equityprice_closing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equityprice",
            name="closing_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
