# Generated by Django 6.0.4 on 2026-04-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0004_merge_0003_portfolio_is_default_0003_priceupdatelog"),
        ("transactions", "0010_alter_equityprice_closing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="portfolios.portfolio",
            ),
        ),
    ]
