# Generated by Django 6.0.4 on 2026-04-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0012_load_asx_equity_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equityprice",
            name="equity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="transactions.equity",
            ),
        ),
    ]
