# Generated by Django 6.0.2 on 2026-03-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomer",
            name="stripeCustomerId",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomer",
            name="stripeSubscriptionId",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.CreateModel(
            name="StripeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripePaymentId", models.CharField(max_length=255)),
                ("currency", models.CharField(default="AUD", max_length=10)),
                ("amount", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="subscriptions.stripecustomer",
                    ),
                ),
            ],
        ),
    ]
