# Generated by Django 6.0.2 on 2026-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_stripecustomer_stripecustomerid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("premium", "Premium"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
