# Generated by Django 6.0.2 on 2026-03-27 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_alter_subscription_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="duration",
        ),
    ]
