# Generated by Django 6.0.2 on 2026-03-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_remove_subscription_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="badge",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
