# Generated by Django 6.0.2 on 2026-04-02 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_subscription_badge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="price",
        ),
    ]
