# Generated by Django 6.0.2 on 2026-04-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
        ("transactions", "0005_asxequitylist_equity_alter_transaction_equity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdings",
            name="equity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="transactions.equity"
            ),
        ),
        migrations.RemoveField(
            model_name="holdings",
            name="total_value",
        ),
        migrations.DeleteModel(
            name="EquityPrice",
        ),
        migrations.DeleteModel(
            name="Equity",
        ),
    ]
