# Generated by Django 6.0.2 on 2026-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0002_alter_holdings_equity_remove_equityprice_equity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
