# Generated by Django 6.0.2 on 2026-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0002_alter_holdings_equity_remove_equityprice_equity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("run_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
