# Generated by Django 6.0.4 on 2026-04-19 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0003_portfolio_is_default"),
        ("portfolios", "0003_priceupdatelog"),
    ]

    operations = []
